INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'saurav@gmail.com', 'Saurav', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'chetan@gmail.com', 'chetan', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'harish@gmail.com', 'Hari1611', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'razia@gmail.com', 'Razia', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'navyab@gmail.com', 'navyaB', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'navyaV@gmail.com', 'navyaV', 'USER');

INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'bindu@gmail.com', 'Bindu@123', 'ADMIN');